### ISSUE TITLE
Add support for ES6 new syntax

### ISSUE THREAD

**Issue by pensierinmusica** [braver/Solarized#45]
Hi,

It'd be awesome if this theme could add support the latest JavaScript syntax, [introduced by ES6](https://github.com/lukehoban/es6features).

This follows the thread started here: https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/75

Thanks!

**Comment by Snack-X** [comment]
Hello,
As I mentioned at [here](https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/75), [I'm trying to land new features of JavaScriptNext](https://github.com/Snack-X/Solarized/tree/feature-jsnext).
Also, I converted plist to YAML to make it easier to edit.

**Comment by braver** [comment]
:+1: I'm for all of this, and will happily pull any improvements that you make. If it's possible, I would prefer snack sized pull requests, like just [the fix you did for variables](https://github.com/Snack-X/Solarized/commit/f89527348d2b728dfe022845d856c28a0f168b12), because that's easier to grok and make sure it all still works together well. I can image full ES6 support to be quite an undertaking, but it would be nice to be able to release improvements as they roll in.

I would prefer to keep the YAML out of the repo though. As much as I understand the win in ease of editing, I want this to be easy to work on without any build/conversion steps (e.g. right from within Github). Sublime Text 3 will be moving away from XML anyway.

**Comment by Snack-X** [comment]
Then I'd better just clean-up(cases of color, indention, order of some rules) existing `.tmTheme` files and add JSNext features.

**Comment by pensierinmusica** [comment]
Thanks @Snack-X and @braver, looking forward to update this from Package Control every time a new ES6 syntax is supported  :)

**Comment by braver** [comment]
It has begun: https://github.com/braver/Solarized/releases/tag/1.5.0

**Comment by pensierinmusica** [comment]
Awesome  :)

@Snack-X and @braver, if you could add supprt for `const

**Comment by pensierinmusica** [comment]
@Snack-X and @braver, `const` should be written uppercase, dividing words with underscores (check [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const)). I just noticed that if I type

```js
const foo = 'foo';
```

It's rendered correctly. But

```js
const BAR = 'bar';
```

It's not.

Can you please check it out? Thanks!

**Comment by pensierinmusica** [comment]
Hi, any update on this?

**Comment by braver** [comment]
I don't have the knowledge (or the time to dig into it) to pull this along. If anyone wants to open up some pull requests I'll happily review and pull them in!

**Comment by pensierinmusica** [comment]
@Snack-X any chance? :)

**Comment by braver** [comment]
@pensierinmusica we kinda did some ES2015 work in #51 and I'm now looking at this. I don't work with ES2015 too much, but I'm definitely open to tweaking this case-by-case.

So about constants, they're now highlighted in blue,
<img width="259" alt="screen shot 2016-04-01 at 19 33 59" src="https://cloud.githubusercontent.com/assets/2543659/14215060/e95873de-f840-11e5-9dc8-e494695695dc.png">

and variables are not.
<img width="272" alt="screen shot 2016-04-01 at 19 34 07" src="https://cloud.githubusercontent.com/assets/2543659/14215064/eca78958-f840-11e5-85ca-cc983ffd7920.png">

If you make a typo and add a lowercase character, it won't be blue so it kinda gives you a hint there.
<img width="264" alt="screen shot 2016-04-01 at 19 35 09" src="https://cloud.githubusercontent.com/assets/2543659/14215070/f0850578-f840-11e5-854c-d3b4b09a8813.png">

How would you like to see this behaviour changed?

**Comment by pensierinmusica** [comment]
Hi @braver, I'd be fine with having constants behave graphically like variables, as they're already distinguished by upper case.

What I definitely fon't like is having the "const" word and the constant itself being in the same blue color.

So, my proposal would be to leave "const" in blue, and have the constant name in gray (like variables). Otherwise if you want to introduce another color that is doable too, although I'm not sure if it's required. Just make sure that "const" and the name use two different, easily distinguishable, colors.

Thanks!

**Comment by braver** [comment]
Ok, sounds good. I agree, let's make the constant grey. I'll push a fix later today!

If you have anything else, please open an issue with a specific case.

**Comment by pensierinmusica** [comment]
Awesome, thanks!

**Comment by pensierinmusica** [comment]
Since you're about to push a fix, it could include syntax highlighting for the [upcoming](https://jakearchibald.com/2014/es7-async-functions/) "async/await" JS pattern that is going to be introduced soon.

![screenshot](https://cloud.githubusercontent.com/assets/3594037/14226302/d7916e46-f8de-11e5-90b6-6fdd94ace319.png)

I guess "async" could be in yellow like "await". Thoughts? Cheers!

**Comment by braver** [comment]
`async` isn't recognised as something special that we can style differently. It's just a `storage.type` like var, const and such. So there isn't much to do there without affecting lots of other stuff as well.

**Comment by pensierinmusica** [comment]
Ok, nevermind 😉
