### ISSUE TITLE
contrast between comments and normal code is gone

### ISSUE THREAD

**Issue by robkorv** [braver/Solarized#48]
![selectie_005](https://cloud.githubusercontent.com/assets/4266355/9810830/aa90a4c2-5873-11e5-8fdd-b8011d4d4e0e.png)

Before the last update, comments where light gray. Can you add that back plz?

**Comment by braver** [comment]
Good catch. Sorry about that. 
Fixed in https://github.com/braver/Solarized/commit/b36ab59ad0c2b0ae5ad74fa1c8a41af3b7200841

**Comment by robkorv** [comment]
tnx! :+1:
