### ISSUE TITLE
Support to highlight line sublime text option

### ISSUE THREAD

**Issue by chronossc** [braver/Solarized#49]
Sublime Text has `highlight_line` option but when set to true the theme not highlight the line.

**Comment by braver** [comment]
Must be something wrong with your setup, because it works fine.

<img width="314" alt="screen shot 2015-10-23 at 08 39 01" src="https://cloud.githubusercontent.com/assets/2543659/10686161/91dfcbb0-7961-11e5-938b-20fc2215a55d.png">
