### ISSUE TITLE
Is there a way to style the sidebar?

### ISSUE THREAD

**Issue by zerodburn** [braver/Solarized#50]
I find it a bit distracting when the colour scheme is set to dark and the sidebar is still in the default colour.

Thanks for the port - I prefer the colours over Sublime's default Solarized theme.

**Comment by braver** [comment]
The sidebar is part of the UI theme and it cannot be controlled from within the colour scheme. Or rather, it *shouldn't*, it's a different kind of package and out of scope of this colour scheme. There are a number of themes that match well with Solarized though, like this one: https://packagecontrol.io/packages/Theme%20-%20Sodarized, so you could install one of those.
