### ISSUE TITLE
Repository image font

### ISSUE THREAD

**Issue by lucas-merlette** [braver/Solarized#54]
Hi,

Sorry that's not really an issue concerning the use of this theme -which is VERY GOOD by the way good job-, but I wondered what the font used in the Sublime Text screenshots is ; I searched nearly everywhere but can't seem to find an answer.

Thanks a lot in advance !
Keep up the good work

**Comment by braver** [comment]
@lucas-merlette it is probably Input, one of my absolute favourite fonts. You can verify (and find a download link) here: http://app.programmingfonts.org
