### ISSUE TITLE
Keywords in C++ not being highlighted correctly.

### ISSUE THREAD

**Issue by chris-oo** [braver/Solarized#57]
Hi,

Certain C++ keywords are not being highlighted like the default color scheme, after an update. Example code:
```
class Test :
    public Interface
{
public:
    virtual
    void
    SomeMethod();

private:
    int SomeData
};
```

Here's how it looks in the default color scheme:
![image](https://cloud.githubusercontent.com/assets/1316989/24383122/f52510e2-130f-11e7-90b4-8021c2c14695.png)

Here's how it looks in the current version:
![image](https://cloud.githubusercontent.com/assets/1316989/24383149/1a63c1e6-1310-11e7-9a8f-142596a6f70e.png)

Note that the C++ keywords public, virtual, and private are not being colored like class, etc. I remember before today that they were colored green, is this a regression?

Thanks!

**Comment by braver** [comment]
Yes, the storage.modifier scope has been enabled for all languages. 

The design and structure of Solarized is really different from the default theme, the default theme is also really limited, so there is no ambition to match it in any way. However, I think a c++ specific tweak makes sense here.
