### ISSUE TITLE
Add tests using Color Scheme Unit

### ISSUE THREAD

**Issue by gerardroche** [braver/Solarized#59]
If I send a PR with tests using [ColorSchemeUnit](https://github.com/gerardroche/sublime_color_scheme_unit), would it be merged?

I will add a basic set of tests and possibly some bug fixes if I find any during testing.

**Comment by braver** [comment]
A testing framework is nice, but I currently have no intention on revising large portions of the source code and as such am not too interested in pre-emptively writing tests. I'm primarily interested in keeping the repository simple to work with and as such have no interest in incorporating anything that builds on third party functionality (and maintaining compatibility).

**Comment by gerardroche** [comment]
Just so you know, adding tests would only add test files in a `tests/` directory. Nothing else would be touched or added.

The test files in the form `tests/test_solarized_dark.php`, `tests/test_solarized_light.php`, `tests/test_solarized_dark.js`, etc.

That's it.

No dependencies. Nothing else required.

Then if you want to run the tests you just install color scheme unit and run the package' color scheme tests.

**Comment by braver** [comment]
Yes, I understand the concept just fine. However, the test files have no function without the test runner, and changes in the test runner, or the syntax definitions for any language, might break or invalidate the tests. Creating tests is work, maintaining tests is work, effort which is usually better spent simplifying the color scheme or making it more robust in different ways. For color schemes I like having a test bed to prevent against regression when refactoring, but only then.
