### ISSUE TITLE
Question about meta.class

### ISSUE THREAD

**Issue by ooJerryLeeoo** [braver/Solarized#63]
Hi @braver, I was wondering why change the `meta.class` color to yellow instead of the text color ?

> The syntax in the screenshot is C++

![screen shot 2017-07-20 at 08 14 53](https://user-images.githubusercontent.com/20783502/28395043-afd7c962-6d23-11e7-8bb8-b4f164ccf4b9.png)

I think the `meta.class` look's better with the text color

![screen shot 2017-07-20 at 08 15 19](https://user-images.githubusercontent.com/20783502/28395028-a3c06102-6d23-11e7-9d36-3bccce5b7ed7.png)

**Comment by braver** [comment]
closed via #64
