### ISSUE TITLE
Asset refs need updating?

### ISSUE THREAD

**Issue by smaili** [braver/Solarized#66]
Based on the comments here - https://forum.sublimetext.com/t/very-colorful-tabs/31244, it looks like the latest update from Sublime is no longer compatible with Solarized?

Screenshot of my own screen as well:

![image](https://user-images.githubusercontent.com/4451986/30390249-51e9a524-986a-11e7-9dcf-16b8081cf505.png)

**Comment by smaili** [comment]
I see.  How can I found out the UI theme?

**Comment by braver** [comment]
Using the command palette, look for `UI: select theme` and try some of the options.

**Comment by smaili** [comment]
Yeah I had tried that, it's just the `Default.sublime-theme`

![image](https://user-images.githubusercontent.com/4451986/30392711-783a8c2c-9872-11e7-81c3-c19accf6562f.png)

Changing to the Adaptive works but I'm more trying to understand why the Default is no longer working as expected :/

**Comment by braver** [comment]
Look for a `Default.sublime-theme` file in your User folder, you may have outdated customisations.

**Comment by smaili** [comment]
Yeah looks like that's no longer compatible :(

I'll have to use the Adaptive theme for now until I have time to look into this more.  Thanks @braver for your time, super appreciative!

**Comment by smaili** [comment]
Feel free to close this 👍
