### ISSUE TITLE
Better installation instructions for macOS users

### ISSUE THREAD

**Issue by pouriaalmassi** [braver/Solarized#70]
A better set of manual installation instructions for macOS users might be something along the following lines:

```
# Open the Terminal app 
# Clone or download this repository. 
git clone https://github.com/braver/Solarized/
cd Solarized
cp *.tmTheme ~/Library/Application\ Support/Sublime Text 3/Packages/User/
# Choose your theme from the Color Scheme menu
```

**Comment by braver** [comment]
Hm, I don't know why I point to the installation instructions for Package Control. However, if you know you can do and want to do manual installation, I'm going to assume you also know how to do so.
