### ISSUE TITLE
Some badges are broken in the README

### ISSUE THREAD

**Issue by moodmosaic** [braver/Solarized#77]
Unsure if it's an actual bug or a Google Chrome issue:

![image](https://user-images.githubusercontent.com/287532/52777316-c5bdc080-3043-11e9-958e-833b4c8808f7.png)

Though, on IE11 seems broken too:

![image](https://user-images.githubusercontent.com/287532/52777422-16351e00-3044-11e9-9fa4-f60394aaa88a.png)

**Comment by braver** [comment]
It’s just missing emoji, your OS and browser don’t have a font with the appropriate characters. 🤷🏼‍♂️

**Comment by moodmosaic** [comment]
Yeah I just noticed that as well. It appears to work fine on macOS and Windows 10. It's only an issue with Windows 8 (I happened to be working on an old VM for a moment).

**Comment by braver** [comment]
Probably also on Linux. Time will heal it 😉
