### ISSUE TITLE
Update from 2.4.0 to 2.5.0 breaks

### ISSUE THREAD

**Issue by Jiehong** [braver/Solarized#78]
Hello,

Updating 2.4.0 to 2.5.0 breaks:

![image](https://user-images.githubusercontent.com/1061229/54139599-36c57d80-4422-11e9-8dd6-12139ca0031b.png)

Restarting Sublime Text does not help.

The console shows the following error:

```sh
Exception in thread Thread-2:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package\package_control/package_cleanup.py", line 81, in run
    os.remove(package_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\Solarized Color Scheme.sublime-package'
```

My settings are as follows:

```json
{
	"caret_extra_width": 14,
	"caret_style": "solid",
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"default_line_ending": "unix",
	"dictionary": "Packages/Language - English/en_GB.dic",
	"dlig": true,
	"draw_white_space": "all",
	"font_face": "Fira Code",
	"font_size": 14,
	"ignored_packages":
	[
		"Solarized Color Scheme",
		"Vintage"
	],
	"tab_size": 2,
	"theme": "Adaptive.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"wide_caret": true
}
```

Do you know what's going on?

**Comment by braver** [comment]
That's really weird. In any case, this color scheme has no runtime code so there is nothing it can do to break anything. Probably some other package that is trying to access it and has it locked, or some other program like a virus scanner.

**Comment by Jiehong** [comment]
It was weird, indeed. Restarting always lead to the same issue.

I tried to remove that package, but the console was somehow showing the same error.

Eventually, I thought that maybe Sublime Merge might be holding that file. So I stopped Sublime Merge, and restarted Sublime Text, and the update happened just fine.

Thanks for your quick answer @braver !
