### ISSUE TITLE
Color scheme changes briefly on start up

### ISSUE THREAD

**Issue by gitressa** [braver/Solarized#81]
I have installed the [Solarized Color Scheme](https://packagecontrol.io/packages/Solarized%20Color%20Scheme) which works fine, using the Solarized Light version, on Ubuntu 18.04.

Recently (even before the update to build 3200) right after first start-up, it briefly changes to a dark color scheme for a few seconds, and then changes back to Solarized Light.

It's not a big deal, more like a slight annoyance ... still, it would be great to get fixed.

**Comment by braver** [comment]
That's not something I did. It sounds like some package is messing with your settings. What packages do you have installed?

**Comment by gitressa** [comment]
I have got a few packages installed ... I'll try to remove the ones I don't use (`A File Icon`, `ExportHtml`, `Xdebug` and `zzz A File Icon zzz`) and check if that fixes it.

**Comment by gitressa** [comment]
I think there was a conflict with one of the packages I removed, since the flicker problem seems to be solved.

**Comment by braver** [comment]
👍🏻

**Comment by gitressa** [comment]
And by the way, thank you for creating Solarized for Sublime Text 3!
