### ISSUE TITLE
Easy way to darken fonts?

### ISSUE THREAD

**Issue by gitressa** [braver/Solarized#82]
I use Eye Saver mode on my monitor, which also lessens the contrast in Solarized ... I wonder if there is a simple parameter to make the font colors a bit darker? If not, can I make just the default text color darker?

My **Preferences** > **Settings**:
```
{
  "color_scheme": "Packages/Solarized Color Scheme/Solarized (light).sublime-color-scheme",
  "font_size": 18,
  "hot_exit": false,
  "remember_open_files": false,
  "tab_size": 2,
  "translate_tabs_to_spaces": true
}
```

**Comment by braver** [comment]
You can override parts of any color scheme, by putting a file with the same name (e.g. `Solarized (light).sublime-color-scheme`) in Packages/User (go to the Packages dir via the Preferences > Browse Packages menu item).

In this case you'd want to override the variables to make the foreground colours more contrasty. So in that new color scheme file you'd put this:

```json
{
    "variables":
    {
        "base03":  "#002b36",
        "base02":  "#073642",
        "base01":  "#586e75",
        "base00":  "#657b83",
        "base0":   "#839496",
        "base1":   "#93a1a1",
        "base2":   "#eee8d5",
        "base3":   "#fdf6e3",
        "yellow":  "#b58900",
        "orange":  "#cb4b16",
        "red":     "#dc322f",
        "magenta": "#d33682",
        "violet":  "#6c71c4",
        "blue":    "#268bd2",
        "cyan":    "#2aa198",
        "green":   "#859900",
    }
}
```

This is good reference for which colours to change:

![solarized-values-light](https://user-images.githubusercontent.com/2543659/54439074-59180d80-4738-11e9-93ec-37aad11b790d.png)

So, I guess you'd want to make base1, base00 and base01 a bit darker. You can even use a few CSS-like tricks here, for instance `color(#657b83 lightness(0.9))` should make that color 10% darker.

**Comment by gitressa** [comment]
Thanks for the thorough explanation! I created the file following your directions, and can now change the fonts. I couldn't make the lightness trick work, but in stead just edited the values from your list directly:

```
{
    "variables":
    {
        "base01":  "#222",
        "base00":  "#333",
        "base1":   "#555",
    }
}
```

**Comment by braver** [comment]
I think I missed a `,` in the example, but great that you found a solution!

**Comment by gitressa** [comment]
I got [HSL](https://www.w3.org/TR/css-color-3/#hsl-color)-values working, to allow retaining the color nuances, and turn it darker by adjusting the `lightness` value:

> HSL colors are encoding as a triple (hue, saturation, lightness).

**Original values converted to HSL**
```
{
    "variables":
    {
        "base01":  "hsl(194, 14%, 40%)",
        "base00":  "hsl(196, 13%, 45%)",
        "base1":   "hsl(180, 7%, 60%)",
    }
}
```
**`lightness`-value reduced with 20**
```
{
    "variables":
    {
        "base01":  "hsl(194, 14%, 20%)",
        "base00":  "hsl(196, 13%, 25%)",
        "base1":   "hsl(180, 7%, 40%)",
    }
}
```
