### ISSUE TITLE
Sublime Text 3.2: block caret colour hard to notice

### ISSUE THREAD

**Issue by Jiehong** [braver/Solarized#83]
Hi,

With Sublime Text 3.2, a new option has been added: `"block_caret": true`. When activated, the caret is now a block, but it's colour fades and becomes very hard to see.

Here is its colour as a line:
![image](https://user-images.githubusercontent.com/1061229/54671538-65b0b300-4af6-11e9-8095-810092b9a6e7.png)

And as a block:
![image](https://user-images.githubusercontent.com/1061229/54671566-7103de80-4af6-11e9-92de-ef15d67d35d7.png)

Would it be possible to give it a more visible colour?

**Comment by pearofducks** [comment]
@Jiehong - There's a new key - `block_caret` - that can be used to style this.

**Comment by braver** [comment]
Thanks for reporting. I opted to use the light background as the block caret color in the dark theme, and vice versa.

**Comment by moodmosaic** [comment]
👍 💯 🎉

**Comment by Jiehong** [comment]
Thanks!
