### ISSUE TITLE
Please add Sublime Merge scopes

### ISSUE THREAD

**Issue by z0rc** [braver/Solarized#84]
See https://github.com/sublimehq/sublime_merge/issues/198 for context and more details.

**Comment by moodmosaic** [comment]
That'd be lovely!

**Comment by braver** [comment]
Well that took a while :D So, 2.7.2 is out now with a first pass at specific colors for Sublime Merge. Let me know what you think and if we should tweak some colors.

**Comment by braver** [comment]
Well that took a while :D So, 2.7.2 is out now with a first pass at specific colors for Sublime Merge. Let me know what you think and if we should tweak some colors.

**Comment by braver** [comment]
Used it for a bit now myself, seems pretty nice. If anything comes up that could be improved, simply open up an issue!

**Comment by Amparose** [comment]
How does one get this to work in Merge?
