### ISSUE TITLE
Scheme absent in Package Control

### ISSUE THREAD

**Issue by mlfoo** [braver/Solarized#85]
The color scheme isn't listed in Package Control.

Here's a GIF demonstrating my attempt to install, which shows four "Solarized" packages, but not this one.

![install-error](https://user-images.githubusercontent.com/45950685/59785193-398e0500-9292-11e9-8e02-a5401b9e90fa.gif)

Even so, the scheme is listed on [packagecontrol.io](https://packagecontrol.io/packages/Solarized%20Color%20Scheme).

Odd. Am I missing something?

**Comment by braver** [comment]
Perhaps you have it installed but disabled?

**Comment by mlfoo** [comment]
Wow. Yes, you are correct.

(head hanging in shame).

**Comment by braver** [comment]
Hey, you're not the first, not going to be the last either ;)
