### ISSUE TITLE
Not work right in Sublime Text 4 Build 4126

### ISSUE THREAD

**Issue by Jagerx** [braver/Solarized#89]
<img width="1280" alt="2022-03-24_22-32-35" src="https://user-images.githubusercontent.com/42521386/159939899-fff1a2b0-c3c8-4079-ad58-9ec1ce301617.png">
I installed Solarized Color Scheme by Package Control. but only "color_scheme" can be changed, "theme" remains no change. 

And I can only see "Solarized(light/dark)" option in "UI: Select Color Scheme" menue, but there is no "Solarized(light/dark)" option in "UI:Select Theme" , How could I do to? Thanks

**Comment by nyx0** [comment]
I got the same question and I got this answer: "because it's a color scheme and not a theme"

**Comment by braver** [comment]
That’s the correct answer. A color scheme is for what your code looks like. A theme is for the UI. Solarized is a color scheme.
