### ISSUE TITLE
Issue with new theme

### ISSUE THREAD

**Issue by minh0824** [braver/Solarized#93]
![Screenshot 2024-08-10 101322](https://github.com/user-attachments/assets/f0132cc8-803e-44e1-8126-ed764ae92883)
![Screenshot 2024-08-10 101233](https://github.com/user-attachments/assets/4dcabf08-07b1-485c-bba7-7f35e43a1dfa)

Windows 11 23H2 (OS Build 22631.3880)
Sublime text 4180

**Comment by braver** [comment]
Oh, interesting, there must be some images missing... 🕵🏻
